/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as DashboardRoute } from "./routes/dashboard";

const DashboardPathRoute = DashboardRoute.update({
  path: "/dashboard",
  getParentRoute: () => rootRoute,
});

export const routeTree = rootRoute.addChildren([DashboardPathRoute]);

/* prettier-ignore-end */
